package finalproject;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author saadw
 */
public class adminlogin extends javax.swing.JFrame {

    /**
     * Creates new form adminlogin
     */
    public adminlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ausername = new javax.swing.JTextField();
        Apass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        jCheckBoxShowpass = new javax.swing.JCheckBox();
        Alogginb = new javax.swing.JButton();
        lbl_Ausername = new javax.swing.JLabel();
        lbl_Apassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(385, 570));
        getContentPane().setLayout(null);

        Ausername.setBackground(new java.awt.Color(0, 153, 153));
        Ausername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Ausername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AusernameActionPerformed(evt);
            }
        });
        Ausername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AusernameKeyReleased(evt);
            }
        });
        getContentPane().add(Ausername);
        Ausername.setBounds(130, 240, 170, 30);

        Apass.setBackground(new java.awt.Color(0, 153, 153));
        Apass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApassActionPerformed(evt);
            }
        });
        Apass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ApassKeyReleased(evt);
            }
        });
        getContentPane().add(Apass);
        Apass.setBounds(130, 330, 170, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 300, 90, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 200, 90, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN LOGIN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 30, 180, 70);

        close1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        close1.setForeground(new java.awt.Color(255, 255, 255));
        close1.setText("X");
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
        });
        getContentPane().add(close1);
        close1.setBounds(360, 10, 20, 20);

        jCheckBoxShowpass.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxShowpass.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxShowpass.setText("Show Password");
        jCheckBoxShowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowpassActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxShowpass);
        jCheckBoxShowpass.setBounds(130, 390, 130, 23);

        Alogginb.setBackground(new java.awt.Color(0, 204, 204));
        Alogginb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Alogginb.setForeground(new java.awt.Color(191, 120, 86));
        Alogginb.setText("LOGIN");
        Alogginb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlogginbActionPerformed(evt);
            }
        });
        getContentPane().add(Alogginb);
        Alogginb.setBounds(150, 480, 100, 23);

        lbl_Ausername.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbl_Ausername.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lbl_Ausername);
        lbl_Ausername.setBounds(130, 270, 130, 20);

        lbl_Apassword.setBackground(new java.awt.Color(255, 0, 51));
        lbl_Apassword.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbl_Apassword.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lbl_Apassword);
        lbl_Apassword.setBounds(130, 360, 140, 20);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\saadw\\OneDrive\\Desktop\\cafe.gif")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 385, 570);

        setSize(new java.awt.Dimension(385, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_close1MouseClicked

    private void jCheckBoxShowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowpassActionPerformed
if(jCheckBoxShowpass.isSelected())
{
    Apass.setEchoChar((char)0);
}
else
{
    Apass.setEchoChar('•');
}

    }//GEN-LAST:event_jCheckBoxShowpassActionPerformed

    private void AlogginbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlogginbActionPerformed

        if(Ausername.getText().trim().isEmpty() && Apass.getText().trim().isEmpty()){
         lbl_Ausername.setText("User name is Empty");
        lbl_Apassword.setText("Password is Empty");
        }
        else if(Ausername.getText().trim().isEmpty()){
            lbl_Ausername.setText("User name is Empty");
        }
        else if(Apass.getText().trim().isEmpty()){
        lbl_Apassword.setText("Password is Empty");    
        }
        else{
        String Auser,Apasss;
        Auser=Ausername.getText();
        Apasss=Apass.getSelectedText();
        if(Auser.equals("admin") || Auser.equals("Admin") && Apasss.equals("1122"))
        {
            AdminPannel ap=new AdminPannel();
            ap.setVisible(true);
        //ap.pack();
        ap.setLocationRelativeTo(null);
        ap.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        }
        else{
       System.out.println("Wrong Input");
            JOptionPane.showMessageDialog(null,"Wrong Username or Password");
        }
        
        }
    }//GEN-LAST:event_AlogginbActionPerformed

    private void AusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AusernameKeyReleased
        lbl_Ausername.setText("");
    }//GEN-LAST:event_AusernameKeyReleased

    private void ApassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApassKeyReleased
        // TODO add your handling code here:
lbl_Apassword.setText("");
    }//GEN-LAST:event_ApassKeyReleased

    private void AusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AusernameActionPerformed

    private void ApassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alogginb;
    private javax.swing.JPasswordField Apass;
    private javax.swing.JTextField Ausername;
    private javax.swing.JLabel close1;
    private javax.swing.JCheckBox jCheckBoxShowpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_Apassword;
    private javax.swing.JLabel lbl_Ausername;
    // End of variables declaration//GEN-END:variables
}
