package finalproject;
import java.io.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class createuser extends javax.swing.JFrame {

    /**
     * Creates new form createuser
     */
    public createuser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Cuser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Cpass = new javax.swing.JPasswordField();
        Rbutton = new javax.swing.JButton();
        Alogginb1 = new javax.swing.JButton();
        lbl_cusername = new javax.swing.JLabel();
        lbl_Cpassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(328, 320));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create User Account");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 360, 50);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(41, 54, 90, 22);

        Cuser.setBackground(new java.awt.Color(0, 153, 153));
        Cuser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Cuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuserActionPerformed(evt);
            }
        });
        Cuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CuserKeyReleased(evt);
            }
        });
        jPanel1.add(Cuser);
        Cuser.setBounds(115, 82, 170, 23);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(41, 126, 90, 22);

        Cpass.setBackground(new java.awt.Color(0, 153, 153));
        Cpass.setPreferredSize(new java.awt.Dimension(6, 23));
        Cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpassActionPerformed(evt);
            }
        });
        Cpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CpassKeyReleased(evt);
            }
        });
        jPanel1.add(Cpass);
        Cpass.setBounds(115, 154, 170, 23);

        Rbutton.setBackground(new java.awt.Color(0, 204, 204));
        Rbutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Rbutton.setForeground(new java.awt.Color(191, 120, 86));
        Rbutton.setText("Create");
        Rbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Rbutton);
        Rbutton.setBounds(76, 220, 100, 23);

        Alogginb1.setBackground(new java.awt.Color(0, 204, 204));
        Alogginb1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Alogginb1.setForeground(new java.awt.Color(191, 120, 86));
        Alogginb1.setText("Done");
        Alogginb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alogginb1ActionPerformed(evt);
            }
        });
        jPanel1.add(Alogginb1);
        Alogginb1.setBounds(194, 220, 100, 23);

        lbl_cusername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_cusername.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_cusername);
        lbl_cusername.setBounds(120, 110, 130, 10);

        lbl_Cpassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_Cpassword.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_Cpassword);
        lbl_Cpassword.setBounds(120, 180, 150, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 350, 280);

        setSize(new java.awt.Dimension(348, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    private void RbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbuttonActionPerformed

        if(Cuser.getText().trim().isEmpty() && Cpass.getText().trim().isEmpty()){
         lbl_cusername.setText("User name is Empty");
        lbl_Cpassword.setText("Password is Empty");
        }
        else if(Cuser.getText().trim().isEmpty()){
            lbl_cusername.setText("User name is Empty");
        }
        else if(Cpass.getText().trim().isEmpty()){
        lbl_Cpassword.setText("Password is Empty");    
        }
        else{
       /* BufferedWriter bufferedwriter=null;
        String myData="ths is my";
        
        try{
            bufferedWriter=new BufferedWriter(new FileWrtiter(new File("Bla.txt")));
            
        }*/
        
        
        String username;
        String password;
        
        do {
        username=Cuser.getText();
        password=Cpass.getText();
       if (username == "admin"|| username == "ADMIN" || username  == "Admin" ){
                JOptionPane.showMessageDialog(null, "Can't Create !");
            }
                
        } while(  username == "admin"|| username == "ADMIN" || username  == "Admin" );
   
        FileWriter filewriter;
        try{
            
            
            filewriter=new FileWriter("Record.txt",true);
            BufferedWriter bufferedWriter = new BufferedWriter(filewriter); 
            bufferedWriter.write("Username"+" :" + username+"  Password"+" :" + password+"\n");
            
               
            JOptionPane.showMessageDialog(null, "Account Created Successfully!");
            bufferedWriter.close();
            
        } catch (IOException ex){
            JOptionPane.showMessageDialog(null, "Error!");
            System.out.println("Error! ");
            
        }
        
        }
    }//GEN-LAST:event_RbuttonActionPerformed

    private void Alogginb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alogginb1ActionPerformed

    AdminPannel ul=new AdminPannel();
    ul.setVisible(true);
        //ul.pack();
        ul.setLocationRelativeTo(null);
        ul.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_Alogginb1ActionPerformed

    private void CuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuserActionPerformed

    private void CpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CpassActionPerformed

    private void CuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CuserKeyReleased
lbl_cusername.setText("");
    }//GEN-LAST:event_CuserKeyReleased

    private void CpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CpassKeyReleased
lbl_Cpassword.setText("");
    }//GEN-LAST:event_CpassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alogginb1;
    private javax.swing.JPasswordField Cpass;
    private javax.swing.JTextField Cuser;
    private javax.swing.JButton Rbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Cpassword;
    private javax.swing.JLabel lbl_cusername;
    // End of variables declaration//GEN-END:variables
}
